server:
  port: 10300
#微服务接入配置
spring:
  application:
    name: oao-id
  cloud:
    loadbalancer:
      retry:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: oao
        weight: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
---

logging:
  level:
    com.oao: debug
  file:
    name: log/${spring.application.name}/${spring.application.name}
