server:
  port: 10200
#微服务接入配置
spring:
  application:
    name: oao-user
  cloud:
    loadbalancer:
      retry:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: oao
        weight: 1
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oao_user?characterEncoding=utf8&useSSL=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 12366$4
    readOnly: false
    maxLifetime: 600000
  redis:
    hostName: 127.0.0.1
    database: 1
    password: 123456
    port: 6379
    timeout: 10000
    pool-config:
      maxIdle: 24
      maxTotal: 24
      minIdle: 8
      maxWaitMillis: 10000
      testOnBorrow: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
---

logging:
  level:
    com.oao: debug
  file:
    name: log/${spring.application.name}/${spring.application.name}
mybatis-plus:
  mapperLocations: classpath*:com/liyu/oao/**/dao/**/*.xml
