management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  config: classpath:log/oao-log-defalut.xml
mybatis-plus:
  mapperLocations: classpath*:com/oao/**/dao/**/*.xml
  global-config:
    db-config:
      logic-delete-field: del  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
feign:
  hystrix:
    enabled: true
